### ISSUE TITLE
mpc_crypto.restoreEddsaKey() return wrong eddsa private key

### ISSUE THREAD

**Issue by progamer71** [unbound-tech/blockchain-crypto-mpc#12]
Refer to tests.py, function eddsa_backup()
we do step
1 backup key
2 verify backup with function mpc_crypto.verifyEddsaBackupKey()
3 restore key from backup with function mpc_crypto.restoreEddsaKey()
we get eddsa private key and public key at this point

I do some test if eddsa private key is corresponds to public key.
I import the eddsa private key to create pynacl's private key 
and retrieve public key from pynacl's private key.

I expect public key retrieved from pynacl's private key should equal to public key from function eddsa_backup() but they are not equal.

My test code is here (the code is adapted from tests.py)
https://drive.google.com/file/d/18Op3KwMywbw3sMMbO1NQJcW5HvwxOxsm/view

Anyway, I have learned a lot from your work.
Thanks you so much.

Best regards,
Phanu C.

**Comment by ghost** [comment]
Hello, I would like to ask you a question.
1. Did the author of the project not do the key storage, only the key backup?
2. Why did I not get the testShare object when recovering the key?
3. Who will ensure the security of the RSA key pair used for key backup? I don't see the MPC implementation of RSA decryption in the code.
Also, can you leave a contact? I want to discuss some of the issues with you in depth, thank you.

**Comment by mkraitsberg** [comment]
Hi, Phanu!

Looks like the issue with your test is that nacl.signing.SigningKey is actually generating a new key while using it's parameter as seed. (See https://pynacl.readthedocs.io/en/stable/_modules/nacl/signing/ )

Best regards,
Michael

**Comment by Philamericus** [comment]
Hi @Eleven-Z. Sorry for the delayed response (There was a problem with notifications). Here's the answers to your questions:

1. The purpose of this project is to demonstrate the MPC capacities of Unbound Tech. Since key storage is an application-dependent feature, it did not fall in the scope of this project.

2. The key recovery procedure only produces the key in plain and does not produce shares.

3. This is the responsibility of the user. This gives the user the flexibility to determine where and how he wants to store the key for backup. For example, the user might use MPC for the backup key
or the user might store the backup key in a secure location.

4. RSA is not included. See [What's included](https://github.com/unbound-tech/blockchain-crypto-mpc#3-whats-included).

5. If you would be so kind to provide us an e-mail address, we would be happy to contact you.

**Comment by ghost** [comment]
> Hi @Eleven-Z. Sorry for the delayed response (There was a problem with notifications). Here's the answers to your questions:
> 
> 1. The purpose of this project is to demonstrate the MPC capacities of Unbound Tech. Since key storage is an application-dependent feature, it did not fall in the scope of this project.
> 2. The key recovery procedure only produces the key in plain and does not produce shares.
> 3. This is the responsibility of the user. This gives the user the flexibility to determine where and how he wants to store the key for backup. For example, the user might use MPC for the backup key
>    or the user might store the backup key in a secure location.
> 4. RSA is not included. See [What's included](https://github.com/unbound-tech/blockchain-crypto-mpc#3-whats-included).
> 5. If you would be so kind to provide us an e-mail address, we would be happy to contact you.

Thanks for your reply, I tried to serialize TestShare into a file in the example, and it cannot be used again after it is retracted again. What is the reason? My email address is zhangshuguang7@126.com

**Comment by Samuel-Ranellucci** [comment]
Hi @Eleven-Z,

We generate a backup of the private EdDSA key and not the seed that was used to generate the EdDSA key. 
NACL generates the private key from a seed.
In the test code, when you try to provide the private EdDSA key, NACL interprets it as a seed and generates an EdDSA key, which will NOT allow you sign messages under the original key. This is why the program causes an error.

I hope this answers your question.

Best Regards,

Samuel Ranellucci

**Comment by ghost** [comment]
> Hi @Eleven-Z,
> 
> We generate a backup of the private EdDSA key and not the seed that was used to generate the EdDSA key.
> NACL generates the private key from a seed.
> In the test code, when you try to provide the private EdDSA key, NACL interprets it as a seed and generates an EdDSA key, which will NOT allow you sign messages under the original key. This is why the program causes an error.
> 
> I hope this answers your question.
> 
> Best Regards,
> 
> Samuel Ranellucci

Assuming that the client is completely cloned by an adversary, and then the adversary takes the cloned ClientShare and performs a signature or other operation, this would be a very serious security issue. While the project provides a SHARE refresh to organize further threats from key leaks as quickly as possible, the key does get leaked. How do you solve this problem?

**Comment by Philamericus** [comment]
Hi @Eleven-Z,

This is what I received from R&D:

No information about the key is revealed due to the following two points.

1) The key is secret as long as the adversary does not have all the shares.
2) The refresh phase completely randomizes the shares. This ensure that after a refresh, the shares held by the adversary become useless.
